# Print semicolons at the ends of statements.
semi: true
# Use single quotes instead of double quotes.
singleQuote: true
# Print trailing commas wherever possible in multi-line objects/arrays.
trailingComma: es5
# Specify the line length that the printer will wrap on.
printWidth: 80
# Number of spaces per indentation-level.
tabWidth: 2
# Indent lines with spaces instead of tabs.
useTabs: false
# Use double quotes in JSX.
jsxSingleQuote: false
# Always include parentheses around a sole arrow function parameter.
arrowParens: always
# Set the line ending style to LF.
endOfLine: lf
# Print spaces between brackets in object literals.
bracketSpacing: true
# Put the > of a multi-line JSX element at the end of the last line instead of being alone on the next line.
jsxBracketSameLine: false
# Wrap markdown text as-is (do not reformat).
proseWrap: preserve
